export const messages = {
  MSG1: "Vui lòng điền đầy đủ thông tin bắt buộc!",
  MSG2: "Thông tin đăng nhập không chính xác. Vui lòng kiểm tra lại tên đăng nhập và mật khẩu.",
  MSG3: "Đăng nhập thành công!",
  MSG4: "Liên kết xác thực đã được gửi thành công!",
  MSG5: "Đã xảy ra lỗi, vui lòng thử lại!",
  MSG6: "Địa chỉ email của bạn đã được xác thực.",
  MSG7: "Đăng xuất thành công!",
  MSG8: "Email không tồn tại.",
  MSG9: "Mã OTP đã được gửi thành công!",
  MSG10: "Mã OTP không hợp lệ!",
  MSG11: "Đặt lại mật khẩu thành công!",
  MSG12: "Mật khẩu cần ít nhất 8 kí tự, chứa ít nhất 1 số và 1 kí tự đặc biệt",
  MSG13: "Mật khẩu cũ không đúng. Vui lòng thử lại!",
  MSG14: "Đổi mật khẩu thành công!",
  MSG15: "Cập nhật thông tin người dùng thành công!",
  MSG16: "Đăng ký thành công!",
  MSG17: "Bạn có chắc chắn muốn xoá các sản phẩm đã chọn không?",
  MSG18: "Sản phẩm đã được xóa khỏi giỏ hàng!",
  MSG19: "Đặt hàng thành công!",
  MSG20: "Đánh giá của bạn đã được gửi thành công!",
  MSG21: "Cập nhật thông tin giao hàng thành công!",
  MSG22: "Thêm người dùng thành công!",
  MSG23: "Chỉnh sửa thông tin người dùng thành công!",
  MSG24: "Bạn có chắc chắn muốn hủy đơn hàng không?",
  MSG25: "Bạn có chắc chắn muốn lưu trữ người dùng không?",
  MSG26: "Chỉnh sửa danh mục sản phẩm thành công!",
  MSG27: "Lưu trữ người dùng thành công!",
  MSG28: "Khôi phục danh mục sản phẩm thành công!",
  MSG29: "Khôi phục sản phẩm thành công!",
  MSG30: "Lưu trữ danh mục sản phẩm thành công!",
  MSG31: "Thêm danh mục sản phẩm thành công!",
  MSG32: "Thêm sản phẩm thành công!",
  MSG33: "Chỉnh sửa sản phẩm thành công!",
  MSG34: "Bạn có chắc chắn muốn lưu trữ sản phẩm không?",
  MSG35: "Lưu trữ sản phẩm thành công!",
  MSG36: "Thêm kích cỡ sản phẩm thành công!",
  MSG37:
    "Không thể xóa kích cỡ sản phẩm khi nó đang được liên kết với các sản phẩm.",
  MSG38: "Xóa kích cỡ sản phẩm thành công!",
  MSG39: "Chỉnh sửa kích cỡ sản phẩm thành công!",
  MSG40: "Cập nhật trạng thái thanh toán thành công!",
  MSG41:
    "Không thể xóa màu sản phẩm khi nó đang được liên kết với các sản phẩm.",
  MSG42: "Xóa màu sắc sản phẩm thành công!",
  MSG43: "Chỉnh sửa màu sắc sản phẩm thành công!",
  MSG44: "Thông tin theo dõi đơn hàng đã được cập nhật!",
  MSG45: "Phản hồi đánh giá thành công!",
  MSG46: `Sản phẩm không đủ số lượng trong kho.`,
  MSG47: "Sản phẩm đã được thêm vào giỏ hàng!",
  MSG48:
    "Địa chỉ email không hợp lệ. Vui lòng nhập lại theo định dạng đúng (ví dụ: example@domain.com).",
  MSG49: "Mật khẩu và mật khẩu xác nhận không trùng khớp. Hãy thử lại.",
  MSG50: "Số điện thoại bạn nhập không hợp lệ. Vui lòng kiểm tra lại.",
  MSG51: "Email đã tồn tại.",
  MSG52: "Đơn hàng đã được hủy thành công!",
  MSG53:
    "Tài khoản của bạn đã bị vô hiệu hóa. Vui lòng liên hệ với quản trị viên.",
  MSG54: "Kích cỡ sản phẩm đã tồn tại!",
  MSG55: "Màu sắc sản phẩm đã tồn tại!",
  MSG56: "Danh mục sản phẩm đã tồn tại!",
  MSG57:
    "Sản phẩm với kích cỡ và màu sắc này đã tồn tại. Vui lòng kiểm tra lại!",
  MSG58: "Khôi phục người dùng thành công!",
  MSG59: "Đánh giá của bạn đã được cập nhật thành công!",
  MSG60: "Xóa đánh giá thành công!",
  MSG61: "Đánh giá của bạn vi phạm quy tắc cộng đồng. Vui lòng thử lại!",
  MSG62: "Phản hồi của bạn vi phạm quy tắc cộng đồng. Vui lòng thử lại!",
  MSG63: "Ẩn đánh giá thành công!",
  MSG64: "Hiển thị đánh giá thành công!",
};
